package java_by_example;

public class Codes {
    
    static String endOfProgramAsker = "\nEnter 'again' to run the program, or enter anything else to go back.";
    static String endOfProgramCodeAsker = "\nWould you like to see the code for the program? (y\\n)";
    
    // Simple Codes
    static String helloWorld = "\nCode for program:\n"
                + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
                + "~ public static void main(String[] args) {  ~\n"
                + "~     System.out.println(\"Hello World!\");   ~\n"
                + "~ }                                         ~\n"
                + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n";
    static String twoIntCompare = "\nCode for program:\n"
                + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
                + "~ static Scanner input = new Scanner(System.in);                          ~\n"
                + "~                                                                         ~\n"
                + "~ public static void main(String[] args) {                                ~\n"
                + "~     System.out.println(\"Enter value one:    \");                         ~\n"
                + "~     final int a = input.nextInt();                                      ~\n"
                + "~                                                                         ~\n"
                + "~     System.out.println(\"Enter value two:    \");                         ~\n"
                + "~     final int b = input.nextInt();                                      ~\n"
                + "~                                                                         ~\n"
                + "~     if(a > b) { System.out.printf(\"%d is greater than %d\", a, b); }     ~\n"
                + "~     else { System.out.printf(\"%d is greater than %d\", b, a); }          ~\n"
                + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n";
    static String threeIntCompare = "\nCode for program:\n"
                + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
                + "~ static Scanner input = new Scanner(System.in);                                             ~\n"
                + "~                                                                                            ~\n"
                + "~ public static void main(String[] args) {                                                   ~\n"
                + "~     System.out.println(\"Enter value one:    \");                                            ~\n"
                + "~     final int a = input.nextInt();                                                         ~\n"
                + "~                                                                                            ~\n"
                + "~     System.out.println(\"Enter value two:    \");                                            ~\n"
                + "~     final int b = input.nextInt();                                                         ~\n"
                + "~                                                                                            ~\n"
                + "~     System.out.println(\"Enter value three:  \");                                            ~\n"
                + "~     final int c = input.nextInt();                                                         ~\n"
                + "~                                                                                            ~\n"
                + "~     if(a > b && a > c){                                                                    ~\n"
                + "~         System.out.printf(\"%d is the largest number out of %d, %d and %d\", a, a, b, c);    ~\n"
                + "~     } else if (b > a && b > c){                                                            ~\n"
                + "~         System.out.printf(\"%d is the largest number out of %d, %d and %d\", b, a, b, c);    ~\n"
                + "~     } else if (c > a && c > b){                                                            ~\n"
                + "~         System.out.printf(\"%d is the largest number out of %d, %d and %d\", c, a, b, c);    ~\n"
                + "~     } else { System.out.println(\"Values are identical!\");                                  ~\n"
                + "~ }                                                                                          ~\n"
                + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n";
    static String evenOrOdd = "\nCode for program:\n"
                + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
                + "~ static Scanner input = new Scanner(System.in);                                        ~\n"
                + "~                                                                                       ~\n"
                + "~ public static void main(String[] args){                                               ~\n"
                + "~     System.out.println(\"Enter a number to see if it is even or odd:    \");            ~\n"
                + "~     final long numb = input.nextLong();                                               ~\n"
                + "~     final String even;                                                                ~\n"
                + "~     even = (numb % 2 == 0) ? \"%d is an even number.\\n\" : \"%d is an odd number.\\n\");   ~\n"
                + "~     System.out.printf(even, numb);                                                    ~\n"
                + "~ }                                                                                     ~\n"
                + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n";
    
    // Loops
    static String counting = "\nCode for program:\n"
                + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
                + "~ static Scanner input = new Scanner(System.in);    ~\n"
                + "~                                                   ~\n"
                + "~ public static void main(String[] args) {          ~\n"
                + "~     System.out.println(\"Enter start value:\\t\");   ~\n"
                + "~     final int start = input.nextInt();            ~\n"
                + "~                                                   ~\n"
                + "~     System.out.println(\"Enter end value:\\t\");     ~\n"
                + "~     final int end = input.nextInt();              ~\n"
                + "~                                                   ~\n"
                + "~     for(int i = start; i <= end; i++) {           ~\n"
                + "~         System.out.printf(\"%d\\n\", i);             ~\n"
                + "~     }                                             ~\n"
                + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n";
    static String table = "\nCode for program:\n"
            + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
            + "~ static Scanner input = new Scanner(System.in);                                   ~\n"
            + "~                                                                               ~\n"
            + "~ public static void main(String[] args) {                                      ~\n"
            + "~     System.out.println(\"Enter base number to see it's times tables:\\t\");      ~\n"
            + "~     final int base = input.nextInt();                                         ~\n"
            + "~                                                                               ~\n"
            + "~     int a = 1;                                                                ~\n"
            + "~     for (int i = base; i <= (base * 12); i += base) {                         ~\n"
            + "~         System.out.printf(\"\\t%d x %d = %2d\\n\", base, a, i);                  ~\n"
            + "~         a++;                                                                  ~\n"
            + "~     }                                                                         ~\n"
            + "~ }                                                                             ~\n"
            + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n";
    
    // Patterns
    static String equilateralTriangle = "\nCode for program:\n"
                + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
                + "~ static Scanner input = new Scanner(System.in);       ~\n"
                + "~                                                      ~\n"
                + "~ public static void main(String[] args) {             ~\n"
                + "~     System.out.println(\"Enter number of rows:\\t\");   ~\n"
                + "~     final int base = input.nextInt();                ~\n"
                + "~                                                      ~\n"
                + "~     int j, i;                                        ~\n"
                + "~     for (i = 1; i <= base; i++) {                    ~\n"
                + "~         for (j=1; j <= base-i; j++) {                ~\n"
                + "~             System.out.print(\" \");                   ~\n"
                + "~         }                                            ~\n"
                + "~         for (j=1; j <= i; j++) {                     ~\n"
                + "~             System.out.print(\"* \");                  ~\n"
                + "~         }                                            ~\n"
                + "~         System.out.print(\"\\n\");                      ~\n"
                + "~     }                                                ~\n"
                + "~ }                                                    ~\n"
                + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n";
    static String upsideDownTriangle = "\nCode for program:\n"
            + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
            + "~ static Scanner input = new Scanner(System.in);          ~\n"
            + "~                                                         ~\n"
            + "~ public static void main(String[] args) {                ~\n"
            + "~     System.out.println(\"Enter amount of rows:\\t\");      ~\n"
            + "~     final int rows = input.nextInt();                   ~\n"
            + "~                                                         ~\n"
            + "~     int i, j;                                           ~\n"
            + "~                                                         ~\n"
            + "~     for (i = 1; i <= rows; i++) {                       ~\n"
            + "~         for (j = 1; j < i; j++) {                       ~\n"
            + "~             System.out.print(\" \");                      ~\n"
            + "~         }                                               ~\n"
            + "~         for (j = i; j <= rows; j++) {                   ~\n"
            + "~             System.out.print(\"* \");                     ~\n"
            + "~         }                                               ~\n"
            + "~         System.out.print(\"\\n\");                         ~\n"
            + "~     }                                                   ~\n"
            + "~ }                                                       ~\n"
            + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n";
    static String pascalsTriangle = "\nCode for program:\n"
                + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
                + "~ public static int factorial(int rows) {                               ~\n"
                + "~     int factorialResult;                                              ~\n"
                + "~     for (factorialResult = 1; rows > 1; rows--) {                     ~\n"
                + "~         factorialResult *= rows;                                      ~\n"
                + "~     }                                                                 ~\n"
                + "~     return factorialResult;                                           ~\n"
                + "~ }                                                                     ~\n"
                + "~                                                                       ~\n"
                + "~ public static int ncr(int rows, int r) {                              ~\n"
                + "~     return factorial(rows) / (factorial(rows - r) * factorial(r));    ~\n"
                + "~ }                                                                     ~\n"
                + "~                                                                       ~\n"
                + "~ static Scanner input = new Scanner(System.in);                        ~\n"
                + "~                                                                       ~\n"
                + "~ public static void main(String[] args) {                              ~\n"
                + "~     System.out.println(\"Enter amount of rows to be printed:\\t\");      ~\n"
                + "~     final int rows = input.nextInt();                                 ~\n"
                + "~     int i, j;                                                         ~\n"
                + "~     for (i=0; i<= rows; i++) {                                        ~\n"
                + "~         for(j=0; j<= rows-i; j++) {                                   ~\n"
                + "~             System.out.print(\"  \");                                   ~\n"
                + "~         }                                                             ~\n"
                + "~         for(j=0; j<=i; j++) {                                         ~\n"
                + "~             System.out.printf(\" %3d\", ExtraMethods.ncr(i, j));        ~\n"
                + "~         }                                                             ~\n"
                + "~         System.out.print(\"\\n\");                                       ~\n"
                + "~ }                                                                     ~\n"
                + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n";

    static String floydsTriangle = "\nCode for Program:\n"
            + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
            + "~ static Scanner input = new Scanner(System.in);                                               ~\n"
            + "~                                                                                              ~\n"
            + "~ public static void main(String[] args) throws IOException, InterruptedException {            ~\n"
            + "~     System.out.println(\"Enter amount of rows to be printed:\\t\");                             ~\n"
            + "~     double rows = input.nextDouble();                                                        ~\n"
            + "~                                                                                              ~\n"
            + "~     int i, j, k = 0;                                                                         ~\n"
            + "~                                                                                              ~\n"
            + "~     aboveMax:                                                                                ~\n"
            + "~         if(rows > 13) {                                                                      ~\n"
            + "~             Main.cls();                                                                      ~\n"
            + "~             System.out.println(\"That value is above the maximum recommened value of 13\\n\"    ~\n"
            + "~                     + \"Are you sure you would like to continue? (y\\n)\");                     ~\n"
            + "~             String condition = input.next();                                                 ~\n"
            + "~             if (condition.equals(\"n\")) {                                                     ~\n"
            + "~                 Main.cls();                                                                  ~\n"
            + "~                 for (int q = 3; q >= 0; q--) {                                               ~\n"
            + "~                     if (q == o) {                                                            ~\n"
            + "~                         System.out.println(\"Restarting\");                                    ~\n"
            + "~                         Thread.sleep(1000)                                                   ~\n"
            + "~                         break;                                                               ~\n"
            + "~                     }                                                                        ~\n"
            + "~                     System.out.printf(\"Restarting program in %d\\n\", q);                      ~\n"
            + "~                     Thread.sleep(1000);                                                      ~\n"
            + "~                     Main.cls();                                                              ~\n"
            + "~                 }                                                                            ~\n"
            + "~                 main();                                                                      ~\n"
            + "~             } else {                                                                         ~\n"
            + "~                 break aboveMax;                                                              ~\n"
            + "~             }                                                                                ~\n"
            + "~         }                                                                                    ~\n"
            + "~                                                                                              ~\n"
            + "~     for (i = 1; i <= rows; i++) {                                                            ~\n"
            + "~         for (j = 1; j <= i; j++) {                                                           ~\n"
            + "~             System.out.printf(\"%3d\", k++)                                                    ~\n"
            + "~         }                                                                                    ~\n"
            + "~         System.out.print(\"\\n\");                                                              ~\n"
            + "~     }                                                                                        ~\n"
            + "~ }                                                                                            ~\n"
            + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n";
    
    // Mathematics
    static String armstrongNumber = "\nCode for program:\n"
            + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
            + "~ static Scanner input = new Scanner(System.in);                                        ~\n"
            + "~                                                                                       ~\n"
            + "~ public static void main(String[] args) {                                              ~\n"
            + "~     System.out.println(\"Enter a number to see if it is an Armstrong number:\\t\");      ~\n"
            + "~     int number = input.next();                                                        ~\n"
            + "~                                                                                       ~\n"
            + "~     int check, rem, sum = 0;                                                          ~\n"
            + "~     check = number;                                                                   ~\n"
            + "~                                                                                       ~\n"
            + "~     while (check != 0) {                                                              ~\n"
            + "~         rem = check % 10;                                                             ~\n"
            + "~         sum += (rem * rem * rem)                                                      ~\n"
            + "~         check = check / 10;                                                           ~\n"
            + "~     }                                                                                 ~\n"
            + "~                                                                                       ~\n"
            + "~     if (sum == number) {                                                              ~\n"
            + "~         System.out.printf(\"%d is an Armstrong number.\", number);                      ~\n"
            + "~     } else {                                                                          ~\n"
            + "~         System.out.printf(\"%d is NOT an Armstrong number.\", number);                  ~\n"
            + "~ }                                                                                     ~\n"
            + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n";

}
